import React from 'react';
import {
  BookOpen,
  List,
  User,
  LogOut,
  X,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  Check,
  CheckCircle,
  AlertCircle,
  Search,
  Eye,
  EyeOff,
  Bell,
  Upload,
  BarChart3,
  PieChart,
  Award,
  MapPin,
  Home,
  Shield,
  CalendarX,
  Download,
  Loader2,
  MoreVertical,
  Plus,
  FileCheck,
  Clock,
  Star,
  Trash2,
  Edit,
  FileText,
  Image as ImageIcon,
  Settings,
  HelpCircle,
  Info,
  UserPlus,
  Camera,
  RefreshCw,
  Flame,
  Cloud,
  QrCode,
  Map,
  Navigation,
  Compass,
  Languages,
  GraduationCap,
  Play,
  Pause,
  Copy,
  ExternalLink,
  Share2,
  Maximize2,
  Globe,
  ShieldCheck,
  Phone,
  Lock,
  Database,
  LayoutDashboard,
  FileSpreadsheet,
  TrendingUp,
  TrendingDown,
  Minus,
  MousePointerClick,
  Zap,
  Users,
  Columns,
  Target,
  ShieldAlert,
  Package,
  MessageSquare,
  Calendar,
  Palette,
  Layout,
  RotateCcw,
  PlusCircle,
  History,
} from 'lucide-react';

export const Icons = {
  History: ({ size = 18, className }: { size?: number; className?: string } = {}) => <History size={size} className={className} />,
  Database: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Database size={size} className={className} />,
  LayoutDashboard: ({ size = 18, className }: { size?: number; className?: string } = {}) => <LayoutDashboard size={size} className={className} />,
  FileSpreadsheet: ({ size = 18, className }: { size?: number; className?: string } = {}) => <FileSpreadsheet size={size} className={className} />,
  TrendingUp: ({ size = 18, className }: { size?: number; className?: string } = {}) => <TrendingUp size={size} className={className} />,
  TrendingDown: ({ size = 18, className }: { size?: number; className?: string } = {}) => <TrendingDown size={size} className={className} />,
  Minus: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Minus size={size} className={className} />,
  MousePointerClick: ({ size = 18, className }: { size?: number; className?: string } = {}) => <MousePointerClick size={size} className={className} />,
  Zap: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Zap size={size} className={className} />,
  Users: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Users size={size} className={className} />,
  Columns: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Columns size={size} className={className} />,
  Target: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Target size={size} className={className} />,
  ShieldAlert: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ShieldAlert size={size} className={className} />,
  Package: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Package size={size} className={className} />,
  MessageSquare: ({ size = 18, className }: { size?: number; className?: string } = {}) => <MessageSquare size={size} className={className} />,
  Calendar: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Calendar size={size} className={className} />,
  Palette: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Palette size={size} className={className} />,
  Layout: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Layout size={size} className={className} />,
  RotateCcw: ({ size = 18, className }: { size?: number; className?: string } = {}) => <RotateCcw size={size} className={className} />,
  PlusCircle: ({ size = 18, className }: { size?: number; className?: string } = {}) => <PlusCircle size={size} className={className} />,
  Lock: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Lock size={size} className={className} />,
  AlertCircle: ({ size = 18, className }: { size?: number; className?: string } = {}) => <AlertCircle size={size} className={className} />,
  Book: ({ size = 18, className }: { size?: number; className?: string } = {}) => <BookOpen size={size} className={className} />,
  BookOpen: ({ size = 18, className }: { size?: number; className?: string } = {}) => <BookOpen size={size} className={className} />,
  Camera: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Camera size={size} className={className} />,
  RefreshCw: ({ size = 18, className }: { size?: number; className?: string }) => <RefreshCw size={size} className={className} />,
  Flame: ({ size = 18, className }: { size?: number; className?: string }) => <Flame size={size} className={className} />,
  Cloud: ({ size = 18, className }: { size?: number; className?: string }) => <Cloud size={size} className={className} />,
  Globe: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Globe size={size} className={className} />,
  ShieldCheck: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ShieldCheck size={size} className={className} />,
  Phone: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Phone size={size} className={className} />,
  QrCode: ({ size = 18, className }: { size?: number; className?: string }) => <QrCode size={size} className={className} />,
  Map: ({ size = 18, className }: { size?: number; className?: string }) => <Map size={size} className={className} />,
  Navigation: ({ size = 18, className }: { size?: number; className?: string }) => <Navigation size={size} className={className} />,
  Compass: ({ size = 18, className }: { size?: number; className?: string }) => <Compass size={size} className={className} />,
  Languages: ({ size = 18, className }: { size?: number; className?: string }) => <Languages size={size} className={className} />,
  GraduationCap: ({ size = 18, className }: { size?: number; className?: string }) => <GraduationCap size={size} className={className} />,
  Play: ({ size = 18, className }: { size?: number; className?: string }) => <Play size={size} className={className} />,
  Pause: ({ size = 18, className }: { size?: number; className?: string }) => <Pause size={size} className={className} />,
  Copy: ({ size = 18, className }: { size?: number; className?: string }) => <Copy size={size} className={className} />,
  ExternalLink: ({ size = 18, className }: { size?: number; className?: string }) => <ExternalLink size={size} className={className} />,
  Share2: ({ size = 18, className }: { size?: number; className?: string }) => <Share2 size={size} className={className} />,
  Maximize2: ({ size = 18, className }: { size?: number; className?: string }) => <Maximize2 size={size} className={className} />,
  List: ({ size = 20, className }: { size?: number; className?: string } = {}) => <List size={size} className={className} />,
  User: ({ size = 18, className }: { size?: number; className?: string } = {}) => <User size={size} className={className} />,
  LogOut: ({ size = 18, className }: { size?: number; className?: string } = {}) => <LogOut size={size} className={className} />,
  X: ({ size = 20, className }: { size?: number; className?: string } = {}) => <X size={size} className={className} />,
  ChevronLeft: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ChevronLeft size={size} className={className} />,
  ChevronRight: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ChevronRight size={size} className={className} />,
  ChevronDown: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ChevronDown size={size} className={className} />,
  ChevronUp: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ChevronUp size={size} className={className} />,
  Check: ({ size = 20, className, strokeWidth = 3 }: { size?: number; className?: string; strokeWidth?: number } = {}) => <Check size={size} className={className} strokeWidth={strokeWidth} />,
  CheckCircle: ({ size = 18, className }: { size?: number; className?: string } = {}) => <CheckCircle size={size} className={className} />,
  Alert: ({ size = 22, className }: { size?: number; className?: string } = {}) => <AlertCircle size={size} className={className} />,
  Search: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Search size={size} className={className} />,
  Eye: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Eye size={size} className={className} />,
  EyeOff: ({ size = 18, className }: { size?: number; className?: string } = {}) => <EyeOff size={size} className={className} />,
  Bell: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Bell size={size} className={className} />,
  Upload: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Upload size={size} className={className} />,
  Chart: ({ size = 20, className }: { size?: number; className?: string } = {}) => <BarChart3 size={size} className={className} />,
  PieChart: ({ size = 20, className }: { size?: number; className?: string } = {}) => <PieChart size={size} className={className} />,
  Award: ({ size = 20, className }: { size?: number; className?: string } = {}) => <Award size={size} className={className} />,
  MapPin: ({ size = 18, className }: { size?: number; className?: string } = {}) => <MapPin size={size} className={className} />,
  Home: ({ size = 20, className }: { size?: number; className?: string } = {}) => <Home size={size} className={className} />,
  Shield: ({ size = 20, className }: { size?: number; className?: string } = {}) => <Shield size={size} className={className} />,
  CalendarX: ({ size = 20, className }: { size?: number; className?: string } = {}) => <CalendarX size={size} className={className} />,
  Download: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Download size={size} className={className} />,
  Loader: ({ size = 32, className = 'animate-spin text-white' }: { size?: number; className?: string } = {}) => <Loader2 size={size} className={className} />,
  MoreVertical: ({ size = 18, className }: { size?: number; className?: string } = {}) => <MoreVertical size={size} className={className} />,
  Plus: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Plus size={size} className={className} />,
  FileCheck: ({ size = 18, className }: { size?: number; className?: string } = {}) => <FileCheck size={size} className={className} />,
  Clock: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Clock size={size} className={className} />,
  Star: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Star size={size} className={className} />,
  Trash: ({ size = 16, className }: { size?: number; className?: string } = {}) => <Trash2 size={size} className={className} />,
  Edit: ({ size = 16, className }: { size?: number; className?: string } = {}) => <Edit size={size} className={className} />,
  FileText: ({ size = 18, className }: { size?: number; className?: string } = {}) => <FileText size={size} className={className} />,
  Image: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ImageIcon size={size} className={className} />,
  Settings: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Settings size={size} className={className} />,
  HelpCircle: ({ size = 18, className }: { size?: number; className?: string } = {}) => <HelpCircle size={size} className={className} />,
  Info: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Info size={size} className={className} />,
  UserPlus: ({ size = 18, className }: { size?: number; className?: string } = {}) => <UserPlus size={size} className={className} />,
  AnimatedTrash: ({ isHovered }: { isHovered: boolean }) => (
    <div
      className={`transition-transform duration-300 ${
        isHovered ? 'scale-125 rotate-12 text-yellow-300' : 'scale-100 text-white'
      }`}
    >
      <Trash2 size={26} />
    </div>
  ),
};
