import React from 'react';
import {
  BookOpen,
  List,
  User,
  LogOut,
  X,
  ChevronLeft,
  ChevronRight,
  Check,
  CheckCircle,
  AlertCircle,
  Search,
  Eye,
  EyeOff,
  Bell,
  Upload,
  BarChart3,
  PieChart,
  Award,
  MapPin,
  Home,
  Shield,
  CalendarX,
  Download,
  Loader2,
  MoreVertical,
  Plus,
  FileCheck,
  Clock,
  Star,
  Trash2,
  Edit,
  FileText,
  Image as ImageIcon,
  Settings,
  HelpCircle,
  Info,
  UserPlus,
  Camera,
  RefreshCw,
  Flame,
  Cloud,
  QrCode,
  Map,
  Navigation,
  Compass,
  Languages,
  GraduationCap,
  Play,
  Pause,
  Copy,
  ExternalLink,
  Share2,
  Maximize2,
  Globe,
  ShieldCheck,
  Phone,
} from 'lucide-react';

export const Icons = {
  Book: ({ size = 18, className }: { size?: number; className?: string } = {}) => <BookOpen size={size} className={className} />,
  BookOpen: ({ size = 18, className }: { size?: number; className?: string } = {}) => <BookOpen size={size} className={className} />,
  Camera: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Camera size={size} className={className} />,
  RefreshCw: ({ size = 18, className }: { size?: number; className?: string }) => <RefreshCw size={size} className={className} />,
  Flame: ({ size = 18, className }: { size?: number; className?: string }) => <Flame size={size} className={className} />,
  Cloud: ({ size = 18, className }: { size?: number; className?: string }) => <Cloud size={size} className={className} />,
  Globe: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Globe size={size} className={className} />,
  ShieldCheck: ({ size = 18, className }: { size?: number; className?: string } = {}) => <ShieldCheck size={size} className={className} />,
  Phone: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Phone size={size} className={className} />,
  QrCode: ({ size = 18, className }: { size?: number; className?: string }) => <QrCode size={size} className={className} />,
  Map: ({ size = 18, className }: { size?: number; className?: string }) => <Map size={size} className={className} />,
  Navigation: ({ size = 18, className }: { size?: number; className?: string }) => <Navigation size={size} className={className} />,
  Compass: ({ size = 18, className }: { size?: number; className?: string }) => <Compass size={size} className={className} />,
  Languages: ({ size = 18, className }: { size?: number; className?: string }) => <Languages size={size} className={className} />,
  GraduationCap: ({ size = 18, className }: { size?: number; className?: string }) => <GraduationCap size={size} className={className} />,
  Play: ({ size = 18, className }: { size?: number; className?: string }) => <Play size={size} className={className} />,
  Pause: ({ size = 18, className }: { size?: number; className?: string }) => <Pause size={size} className={className} />,
  Copy: ({ size = 18, className }: { size?: number; className?: string }) => <Copy size={size} className={className} />,
  ExternalLink: ({ size = 18, className }: { size?: number; className?: string }) => <ExternalLink size={size} className={className} />,
  Share2: ({ size = 18, className }: { size?: number; className?: string }) => <Share2 size={size} className={className} />,
  Maximize2: ({ size = 18, className }: { size?: number; className?: string }) => <Maximize2 size={size} className={className} />,
  List: () => <List size={20} />,
  User: () => <User size={18} />,
  LogOut: () => <LogOut size={18} />,
  X: () => <X size={20} />,
  ChevronLeft: () => <ChevronLeft size={18} />,
  ChevronRight: () => <ChevronRight size={18} />,
  Check: () => <Check size={20} strokeWidth={3} />,
  CheckCircle: ({ size = 18, className }: { size?: number; className?: string } = {}) => <CheckCircle size={size} className={className} />,
  Alert: () => <AlertCircle size={22} />,
  Search: () => <Search size={18} />,
  Eye: () => <Eye size={18} />,
  EyeOff: () => <EyeOff size={18} />,
  Bell: () => <Bell size={18} />,
  Upload: () => <Upload size={18} />,
  Chart: () => <BarChart3 size={20} />,
  PieChart: () => <PieChart size={20} />,
  Award: () => <Award size={20} />,
  MapPin: () => <MapPin size={18} />,
  Home: () => <Home size={20} />,
  Shield: () => <Shield size={20} />,
  CalendarX: () => <CalendarX size={20} />,
  Download: ({ size = 18, className }: { size?: number; className?: string } = {}) => <Download size={size} className={className} />,
  Loader: () => <Loader2 size={32} className="animate-spin text-white" />,
  MoreVertical: () => <MoreVertical size={18} />,
  Plus: () => <Plus size={18} />,
  FileCheck: () => <FileCheck size={18} />,
  Clock: () => <Clock size={18} />,
  Star: () => <Star size={18} />,
  Trash: () => <Trash2 size={16} />,
  Edit: () => <Edit size={16} />,
  FileText: () => <FileText size={18} />,
  Image: () => <ImageIcon size={18} />,
  Settings: () => <Settings size={18} />,
  HelpCircle: () => <HelpCircle size={18} />,
  Info: () => <Info size={18} />,
  UserPlus: () => <UserPlus size={18} />,
  AnimatedTrash: ({ isHovered }: { isHovered: boolean }) => (
    <div
      className={`transition-transform duration-300 ${
        isHovered ? 'scale-125 rotate-12 text-yellow-300' : 'scale-100 text-white'
      }`}
    >
      <Trash2 size={26} />
    </div>
  ),
};
